version: '3.3'
services:
   postgres:
     image: postgres:10
     volumes:
       - /srv/bdv_redmine/postgresql-data:/var/lib/postgresql/data
     environment:
       POSTGRES_PASSWORD: 12345678
       POSTGRES_DB: "redmine"
       PGDATA: "/var/lib/postgresql/data"
     restart: always
   redmine:
     build:
       context: .
     image: redmine:custom
     ports:
       - 80:3000
     volumes:
       - /srv/bdv_redmine/docker_redmine-plugins:/usr/src/redmine/plugins
       - /srv/bdv_redmine/docker_redmine-themes:/usr/src/redmine/public/themes
       - /srv/bdv_redmine/docker_redmine-data:/usr/src/redmine/files
     environment:
       REDMINE_DB_POSTGRES: "postgres"
       REDMINE_DB_USERNAME: "postgres"
       REDMINE_DB_PASSWORD: 12345678
       REDMINE_DB_DATABASE: "redmine"
       REDMINE_SECRET_KEY_BASE: "…"
     restart: always
